name: build
on: [push]
defaults:
  run:
    working-directory: repo
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: [ '6.7', '6.12', '7.0', '7.9', '8.0', stable ]
    steps:
    - uses: actions/checkout@v2
      with: { path: repo }
    - uses: Bogdanp/setup-racket@v1.5
      with:
        version: ${{ matrix.racket-version }}
        dest: '$GITHUB_WORKSPACE/racket'
        sudo: never
    - name: install
      run: raco pkg install --installation --auto --link threading-{doc,lib,test}
    - name: test
      run: raco test -ep threading-{doc,lib,test}

    - name: deploy_docs
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && matrix.racket-version == 'stable' }}
      run: |
        set -e
        scribble +m --redirect https://docs.racket-lang.org/local-redirect/index.html \
          --htmls --dest-name docs threading-doc/scribblings/threading.scrbl
        cd docs
        git init -b gh-pages
        git config user.name 'GitHub Actions'
        git config user.email 'lexi.lambda@gmail.com'
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push --force 'https://lexi-lambda:${{ github.token }}@github.com/${{ github.repository }}' gh-pages
